Add verbose option, add apps option, and update filter option
sindresorhus/tasklist pull request #7
Opened 2017-03-03 17:10 UTC by MarkTiedemann

My first pull request. :)

- Adds a `verbose` option to improve performance (see: [https://github.com/sindresorhus/tasklist/issues/6](https://github.com/sindresorhus/tasklist/issues/6])
- Adds an `apps` option (to return only Windows Store Apps)
- Makes the `filter` option accept not only a filter array, but also a single filter string

2017-03-03 17:18 UTC, MarkTiedemann commented
CI failed for `nodejs_version=0.12` with the following output:

```
const debug = require('debug')('xo');
^^^^^
SyntaxError: Use of const in strict mode.
```

Should support for Node v0.12 get dropped or should the `xo` devDependency be downgraded?

2017-03-06 19:55 UTC, sindresorhus commented
> Should support for Node v0.12 get dropped or should the xo devDependency be downgraded?

I will do it after this PR. Just ignore Node.js 0.12 failures for now.

2017-03-06 19:56 UTC, sindresorhus requested changes

2017-03-06 19:56 UTC, sindresorhus commented on index.js
> +	if (Array.isArray(opts.filter)) {
I prefer to keep it `Array` only. I don't like mixing types with little benefit.

2017-03-06 19:56 UTC, sindresorhus commented on readme.md
> +Return verbose results (default: `false`).
Write the default value like done here: https://github.com/sindresorhus/boxen#borderstyle

2017-03-06 19:56 UTC, sindresorhus commented on readme.md
> -		windowTitle: 'Task Host Window'
I think it's useful for people to see the properties like this with values, so maybe add another example in the `verbose` option section and show these.

2017-03-06 23:19 UTC, MarkTiedemann commented
I have made the changes you requested and even fixed a bug in my code. :)

- Make test cases check all properties
- Revert making `memUsage` a `verbose` property (which it is not)
- Revert making `filter` option accept strings
- Add example to `verbose` option documentation
- Change formatting of default values in documentation

2017-03-07 09:57 UTC, MarkTiedemann commented
Just noticed CI failed, and for good reason:
- It seems like `windowTitle` won't be set in the CI env
- The `apps` version returns different rows: 
    - Specifically, it does not have `sessionName` and `sessionNumber`, but instead it has `packageName`
    - In `verbose` mode, it has both `sessionName` and `sessionNumber` as well as `packageName`

Gonna update the PR as soon as possible. :)

2017-03-29 11:51 UTC, MarkTiedemann commented
Earlier CI failed on Node 0.12 with linting errors, now it failed on Node 4, too.

2017-04-23 16:50 UTC, sindresorhus commented
@MarkTiedemann What's the status of this PR? :)

2017-04-24 10:07 UTC, MarkTiedemann commented
Well, I (almost) forgot about the PR. ;)

But thanks to your question, last night I spent 2-3 hours revisiting, upgrading, re-testing, fixing, and completely refactoring the old code. :)

Not 100% happy with the results yet, and some documentation is still missing, but I'm probably gonna push the results in the next few days.

PS: Last time I worked on this PR a couple of weeks ago, I created a streaming version of this module: [tasklist-stream](https://github.com/MarkTiedemann/tasklist-stream). I think once this PR is done, we could perhaps merge both in some way (they do "share" a lot of code already ...).

2017-04-24 23:36 UTC, MarkTiedemann commented
@sindresorhus Here's my refactoring:

 - Update Node versions in appveyor.yml
 - Update dependencies
 - Use const instead of var
 - Use () => {} instead of function() {}
 - Remove Promise ponyfill
 - Remove 'N/A' check due to failure on non-English systems
 - Make the tests cases cover all returned tasks

Hope you like it. :)

2017-04-30 11:27 UTC, sindresorhus requested changes
Looks really good. Just some minor nitpick.

2017-04-30 11:27 UTC, sindresorhus commented on test.js
> +const makeTest = (options, t) => {
Can you use a [test macro](https://github.com/avajs/ava#test-macros) instead?

2017-04-30 11:27 UTC, sindresorhus commented on test.js
> +		tasks.forEach(task => {
Use a for-of loop.

2017-04-30 11:27 UTC, sindresorhus commented on test.js
> +const tasklist = require('./');
Don't change this.

2017-04-30 11:27 UTC, sindresorhus commented on package.json
> +    "xo": "^0.18.1"
Don't change this.

2017-04-30 11:27 UTC, sindresorhus commented on package.json
> +    "test": "xo --fix && ava --verbose"
Don't change this.

2017-04-30 11:27 UTC, sindresorhus commented on package.json
> +    "node": ">=4.0.0"
```
"node": ">=4"
```

2017-04-30 11:27 UTC, sindresorhus commented on test.js
> +	return tasklist(options).then(tasks => {
Use async/await

2017-04-30 11:27 UTC, sindresorhus commented on index.js
> +		options.filter.forEach(fi => args.push('/fi', fi));
Use for-of loop.

2017-04-30 11:27 UTC, sindresorhus commented on index.js
> +	const options = opts || {};
Don't change this. I have it like this so it will be super easy to change to default parameters when I can target Node.js 6.

2017-04-30 11:57 UTC, MarkTiedemann commented on index.js
> +		options.filter.forEach(fi => args.push('/fi', fi));
There was no for-loop before. I'm gladly changing it, but may I ask why?

2017-04-30 11:58 UTC, MarkTiedemann commented on index.js
> +	const options = opts || {};
I didn't think about that. Thanks for explaining. :)

2017-04-30 12:00 UTC, MarkTiedemann commented on test.js
> +const tasklist = require('./');
I didn't like the inconsistency of having require statements in the index file and import statements in the test file. But I guess your plan is to change to import statements everywhere in the long run, so yeah, gladly changing it back. :)

2017-04-30 12:04 UTC, MarkTiedemann commented on test.js
> +const makeTest = (options, t) => {
Been using ava since .9, I totally missed that you support test macros now. Thanks for the advice!

2017-04-30 12:53 UTC, sindresorhus commented on index.js
> +		options.filter.forEach(fi => args.push('/fi', fi));
It's faster. I'm trying to use it over forEach whenever possible. So for consistency too. And I don't like inline arrow functions for things that doesn't return anything. Makes the code harder to read.

2017-04-30 13:34 UTC, MarkTiedemann commented on index.js
> +		options.filter.forEach(fi => args.push('/fi', fi));
Okay, I understand that. Thanks for explaining!

PS: I have fixed the requested changes. :)

2017-05-01 08:52 UTC, sindresorhus approved these changes

2017-05-01 09:00 UTC, merged

2017-05-01 09:00 UTC, sindresorhus commented
Looks great. Thank you @MarkTiedemann :)

2017-05-01 09:02 UTC, sindresorhus commented
Would you be interested in being a maintainer here? I don't think this module requires much more work, so it's mostly just to highlight your contribution here in the readme.

2017-05-01 10:21 UTC, MarkTiedemann commented
Yeah, sure. :) Thanks a lot!

Well, there's some work I'd like to do here in the time to come:
- Implement the `/apps` flag
- Implement the `/m` module flag
- Implement the `/svc` service flag
- Make a streaming interface available (I already created a prototype at [tasklist-stream](https://github.com/MarkTiedemann/tasklist-stream), but there's more work to be done there, too. And I'm not sure how to "merge" both modules - if they should be merged at all. 
- As per `tasklist /?`, `windowTitle` and `status` filters are not supported when querying a remote machine. I'd like to implement a check for that, and also test whether this case breaks the code of this module in any way.

2017-05-01 10:46 UTC, sindresorhus commented
Awesome! Could you put the above into an issue with checklists?

2017-05-01 13:53 UTC, MarkTiedemann commented
Yeah, sure. See: https://github.com/sindresorhus/tasklist/issues/8.